# Generated by Django 5.1.7 on 2025-03-26 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('articleId', models.IntegerField()),
                ('quantiteDisponible', models.IntegerField()),
                ('seuilAlerte', models.IntegerField()),
            ],
        ),
    ]
