# Generated by Django 5.1.7 on 2025-03-26 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('stockId', models.IntegerField()),
                ('DateRapport', models.DateField()),
                ('MouvementDeStock', models.CharField(max_length=20)),
                ('EtatStock', models.CharField(max_length=20)),
                ('Vente', models.CharField(max_length=20)),
                ('Approvisionnement', models.CharField(max_length=20)),
            ],
        ),
    ]
