# Generated by Django 5.1.7 on 2025-03-26 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fournisseurId', models.IntegerField()),
                ('dateCommande', models.DateField()),
                ('statut', models.CharField(max_length=20)),
            ],
        ),
    ]
