# Generated by Django 5.1.7 on 2025-03-26 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=20)),
                ('contact', models.CharField(max_length=20)),
                ('adresse', models.CharField(max_length=20)),
            ],
        ),
    ]
