# Generated by Django 5.1.7 on 2025-04-12 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseur', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fournisseur',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
