# Generated by Django 5.1.7 on 2025-04-06 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_groups_user_is_active_user_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nom',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
