# Generated by Django 5.1.7 on 2025-04-08 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_nom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='nom',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(max_length=30),
        ),
    ]
